feat(footer): add footer to layout
arnaud512/worldify pull request #26
Opened 2020-10-06 16:10 UTC by AaronCGoidel

add footer element to every page through index.html
add styling for footer stuck to bottom of page

Closes: #21

2020-10-06 18:31 UTC, arnaud512 commented
Hey! thanks for the pr!
Can you add it in an angular component instead of the index.html?

2020-10-06 18:31 UTC, arnaud512 requested changes

2020-10-06 18:31 UTC, arnaud512 commented on src/index.html
> +  <footer>
Can you move it to an Angular component?

2020-10-06 18:31 UTC, arnaud512 commented on src/styles.css
> +footer {
and move this in that component?

2020-10-06 23:35 UTC, AaronCGoidel commented
Will do. I'll put it in `src/app/footer`

2020-10-07 00:32 UTC, arnaud512 approved these changes

2020-10-07 00:33 UTC, arnaud512 commented
Hey @AaronCGoidel it's good for me! I'll merge it! thanks!

2020-10-07 00:33 UTC, merged