Added Favorites Functionality
arnaud512/worldify pull request #39
Opened 2020-10-08 12:54 UTC by adhammo

Resolves #38.

I added a "love" button to add a playlist to favorites which will add it to local storage and also added a jumbotron to display favorite playlists.

2020-10-09 03:54 UTC, arnaud512 requested changes

2020-10-09 03:54 UTC, arnaud512 commented on src/app/home/home.component.ts
> +    {
brackets on the same line please :)

2020-10-09 03:56 UTC, arnaud512 commented
Wow really nice looking!! I really like it!
Can you add this feature inside genres/moods items? (ex: http://localhost:4200/playlists/toplists?name=Top%20Lists)
I will merge it once done!

2020-10-09 06:03 UTC, adhammo commented
Hey, @arnaud512.

I added favorites functionality to the genres and playlists.

2020-10-10 14:48 UTC, adhammo commented
@arnaud512, can you review the changes?

2020-10-11 23:50 UTC, arnaud512 commented
Oups I was not as precise as I thought! 
I would like a unique place in the app to get all my favorite items.
So that place at home is where you will see all your favorites items! (from home and from genres/moods)
It that correct for you?

2020-10-11 23:51 UTC, arnaud512 commented
But after that, it will be perfect for me!

2020-10-12 05:10 UTC, adhammo commented
I added the favorites page

2020-10-12 12:58 UTC, arnaud512 commented
Ahh!! no! not a favorite page!
A unique jumbotron called "favorite" at home. Just that!
That gets all your favorites from all the app.
No need to distinguish from where they are coming!

2020-10-18 21:54 UTC, closed without merging